### ISSUE TITLE
NER english

### ISSUE THREAD

**Issue by fasteddys** [JnRMnT/ZemberekDotNet#2]
Hello how can we switch this to english, please share some guidaance

**Comment by JnRMnT** [comment]
Hi @fasteddys , thanks for your interest in the library but i have to note that i am not the original creator of the library and this is simply a .NET Port of https://github.com/ahmetaa/zemberek-nlp. Having said that, it would be more suitable to ask for guidance there. But as far as i know, it is designed to work with Turkish language but techncially it should be possible to convert it to work with English as well. Searching "Turkish" inside the solution would be a good start to understand where you need to implement the English equivelants.
